# .gitlab-ci.yml

image: golang:1.18

stages:
  - build
  - test

build:
  stage: build
  script:
    - go build hello.go
  artifacts:
    paths:
      - hello

test:
  stage: test
  script:
    - ./hello
